### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by wfxphoebus** [coolcooldee/sloth#3]
ERROR [com.github.coolcooldee.sloth.Application.main()] (AbstractGeneratorStrategy.java:234) - Can not found the template file, path is "D:\WebProjects\sloth\target\classes\template\common\deploy.sh.ftl. "
java.io.FileNotFoundException: Template "deploy.sh.ftl" not found.

但是，我在目录下面可以找到这个文件

**Comment by coolcooldee** [comment]
感谢你的反馈的 Issue， 已经 fixed 了这个问题。
该问题是因为在 Windows 下和Linux 路径分隔符不兼容问题，在Windows中的文件路径格式为 D:\source\1.sh，而在linux 中的文件路径格式为 /source/1.sh 。所以在包含路径分隔符的地址做了替换，path.replaceAll("\\\\","/")。
未在 Windows OS 测试，如果还有遗漏，麻烦提交一个PR给我。

**Comment by wfxphoebus** [comment]
还是存在的，在window环境 ，应该是你说的问题，这是我更新代码之后又执行的 日志：
D:\WebProjects\sloth>mvn exec:java -Dexec.args="-path/workspaces/mySlothProject -packagecom.test -h127.0.0.1 -P3306 -uroot -p -dtest -strategyssm"  -Dexec.cleanupDaemonThreads=false -Dexec.mainClass="com.github.coolcooldee.sloth.Application"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sloth 1.0.1-snapshot
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ sloth ---
2016-12-16 11:38:30.900 ERROR [com.github.coolcooldee.sloth.Application.main()] (AbstractGeneratorStrategy.java:234) - Can not found the template file, path is "D:/WebProjects/sloth/target/classes/template/common/deploy.sh.ftl. "
java.io.FileNotFoundException: Template "deploy.sh.ftl" not found.
        at freemarker.template.Configuration.getTemplate(Configuration.java:742)
        at freemarker.template.Configuration.getTemplate(Configuration.java:665)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.gen(AbstractGeneratorStrategy.java:226)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.baseGen(AbstractGeneratorStrategy.java:205)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.baseGen(AbstractGeneratorStrategy.java:188)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.baseGen(AbstractGeneratorStrategy.java:183)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.genEnableGeneratedFileIn(AbstractGeneratorStrategy.java:145)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.genEnableGeneratedFileIn(AbstractGeneratorStrategy.java:86)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.execute(AbstractGeneratorStrategy.java:42)
        at com.github.coolcooldee.sloth.generate.Generator.execute(Generator.java:26)
        at com.github.coolcooldee.sloth.Application.main(Application.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: IOException occur , please check !!
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.gen(AbstractGeneratorStrategy.java:236)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.baseGen(AbstractGeneratorStrategy.java:205)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.baseGen(AbstractGeneratorStrategy.java:188)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.baseGen(AbstractGeneratorStrategy.java:183)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.genEnableGeneratedFileIn(AbstractGeneratorStrategy.java:145)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.genEnableGeneratedFileIn(AbstractGeneratorStrategy.java:86)
        at com.github.coolcooldee.sloth.generate.strategy.AbstractGeneratorStrategy.execute(AbstractGeneratorStrategy.java:42)
        at com.github.coolcooldee.sloth.generate.Generator.execute(Generator.java:26)
        at com.github.coolcooldee.sloth.Application.main(Application.java:23)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.786 s
[INFO] Finished at: 2016-12-16T11:38:30+08:00
[INFO] Final Memory: 23M/222M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project sloth: An exception occured while executing the Java class. null: InvocationTargetException: IOException occur , please check !! -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by coolcooldee** [comment]
看了你的日志，我对Windows下的文件Path做了批量修复，问题已Fixed，谢谢 ！
