### ISSUE TITLE
发现的问题

### ISSUE THREAD

**Issue by biezhi** [coolcooldee/sloth#4]
**问题**

1. 在生成项目的时候默认生成了名称为`mySlothProject`的项目
2. 我指定的框架策略是`ssm`，生成出来是基于springboot的
3. 在默认生成的工程中启动后访问`http://127.0.0.1:8081/p/t_user/create`报错

```java
when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: ${autoIncrement?c} auto-escaped [in template "TUserCreate.ftl" at line 64, column 117] ---- Java stack trace (for programmers): ---- freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...] at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131) at freemarker.core.UnexpectedTypeException.newDesciptionBuilder(UnexpectedTypeException.java:77) at freemarker.core.UnexpectedTypeException.(UnexpectedTypeException.java:40) at freemarker.core.BuiltInsForMultipleTypes$AbstractCBI._eval(BuiltInsForMultipleTypes.java:639) at freemarker.core.Expression.eval(Expression.java:78) at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82) at freemarker.core.BuiltInForString._eval(BuiltInForString.java:26) at freemarker.core.Expression.eval(Expression.java:78) at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82) at freemarker.core.DollarVariable.accept(DollarVariable.java:41) at freemarker.core.Environment.visit(Environment.java:324) at freemarker.core.MixedContent.accept(MixedContent.java:54) at freemarker.core.Environment.visit(Environment.java:324) at freemarker.core.EscapeBlock.accept(EscapeBlock.java:48) at freemarker.core.Environment.visit(Environment.java:324) at freemarker.core.MixedContent.accept(MixedContent.java:54) at freemarker.core.Environment.visit(Environment.java:324) at freemarker.core.Environment.process(Environment.java:302) at freemarker.template.Template.process(Template.java:325) at 
```

**Comment by coolcooldee** [comment]
1.通过 -projectname 生成参数来自定义项目的名称（readme已补充说明）
2.目前的框架都是机遇springboot，区别在持久层，可以灵活选择
3. fixed

Thanks！
